name: Docker hub login
on: push
jobs:
    docker-login:
        runs-on: ubuntu-latest
        name: Login job
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1 
              with:
                  username: ${{ secrets.DOCKER_USERNAME}}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN}}