name: Docker hub login
on: push
jobs:
    docker-login:
        runs-on: ubuntu-latest
        name: Login job
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1 
              with:
                  username: ${{ secrets.DOCKER_USERNAME}}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
            - name: Pull Nginx image
              run: |
                docker pull nginx:latest

            - name: Tag Nginx image
              run: |
                docker tag nginx:latest eanzo24/nginx:latest 

            - name: Push Nginx image to Docker Hub
              run: |
                docker push eanzo24/nginx:latest  
#            - name: Build and push to docker
#              uses: docker/build-push-action@v2
#              with:
#                  context: /
#                  push: true
#                  tags: eanzo24/nginx:latest, eanzo24/nginx:${{ github.run_number }}